version: '3'

services:
  db:
    image: mariadb:10
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=Tmaltmfhdn
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.d/:/docker-entrypoint-initdb.d/
    networks:
      pdns:
        ipv4_address: 192.168.255.2  
        
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "192.168.255.2"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "Tmaltmfhdn"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      -  ./npm/data:/data
      -  ./npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      pdns:
        ipv4_address: 192.168.255.254

networks:
  pdns:
    ipam:
      config:
        - subnet: 192.168.255.0/24
          gateway: 192.168.255.1

